### ISSUE TITLE
Sign In - Cannot read property 'use_req_user_jwt' of undefined

### ISSUE THREAD

**Issue by saisk73** [digifi-io/loan-origination-system#118]
I couldn't sign in to the account.
The api response is 
`{"message":"Cannot read property 'use_req_user_jwt' of undefined","stack":"TypeError: Cannot read property 'use_req_user_jwt' of undefined\n    at Promise (/var/www/digifi/node_modules/periodicjs.ext.oauth2server/utilities/auth.js:18:23)\n    at new Promise (<anonymous>)\n    at validateUserForUnauthenticatedRequest (/var/www/digifi/node_modules/periodicjs.ext.oauth2server/utilities/auth.js:15:10)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}`

I have installed all the packages according to the documentation, but couldn't figure out the issue.
I have followed all the steps but I couldn't find where should I exactly replace client_secret in YOUR_REACTAPP_CLIENT_SECRET.
Can anyone help me figure this out?

**Comment by saisk73** [comment]
Sorry it was cache issue closing the issue.
