### ISSUE TITLE
Error on unser login/account creation

### ISSUE THREAD

**Issue by hmercade** [digifi-io/loan-origination-system#17]
Hello, after setting it up I get the following error when clicking on the submit buttons for sign in or account creation:

```
2019-08-27T08:41:40.199Z - error: Cannot read property 'pathname' of undefined TypeError: Cannot read property 'pathname' of undefined
    at /home/devop/loan-origination-system/content/container/decision-engine-service-container/controllers/transform.js:14:81
    at Layer.handle [as handle_request] (/home/devop/loan-origination-system/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/devop/loan-origination-system/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/devop/loan-origination-system/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/devop/loan-origination-system/node_modules/express/lib/router/layer.js:95:5)
    at /home/devop/loan-origination-system/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/devop/loan-origination-system/node_modules/express/lib/router/index.js:335:12)
    at next (/home/devop/loan-origination-system/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/home/devop/loan-origination-system/node_modules/express/lib/router/index.js:174:3)
    at router (/home/devop/loan-origination-system/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/devop/loan-origination-system/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/devop/loan-origination-system/node_modules/express/lib/router/index.js:317:13)
    at /home/devop/loan-origination-system/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/devop/loan-origination-system/node_modules/express/lib/router/index.js:335:12)
    at next (/home/devop/loan-origination-system/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/home/devop/loan-origination-system/node_modules/express/lib/router/index.js:174:3)
    at router (/home/devop/loan-origination-system/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/devop/loan-origination-system/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/devop/loan-origination-system/node_modules/express/lib/router/index.js:317:13)
    at /home/devop/loan-origination-system/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/devop/loan-origination-system/node_modules/express/lib/router/index.js:335:12)
    at Immediate.next (/home/devop/loan-origination-system/node_modules/express/lib/router/index.js:275:10)
    at Immediate._onImmediate (/home/devop/loan-origination-system/node_modules/express/lib/router/index.js:635:15)
    at processImmediate (internal/timers.js:441:21)
    at process.topLevelDomainCallback (domain.js:131:23) 
{
  err: {},
  ipinfo: {
    date: 2019-08-27T08:41:40.199Z,
    'x-forwarded-for': undefined,
    remoteAddress: '::ffff:83.45.92.211',
    originalUrl: '/auth/login',
    headerHost: 'xxx.xxx.com:8788',
    userAgent: 'Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0',
    referer: 'https://xxx.xxx.com:8788/',
    user: {},
    osHostname: 'digifi-1'
  }
}
```

I tried to fix it by modifying `content/container/decision-engine-service-container/controllers/transform.js` so that it gets `req._originalUrl`, and then it worked, but after login I get the following:

```
2019-08-27T09:52:26.983Z - error: Cannot set property 'userprivilegesdata' of undefined TypeError: Cannot set property 'userprivilegesdata' of undefined
    at Object.setPrivilegesOnUser (/home/devop/loan-origination-system/node_modules/periodicjs.ext.user_access_control/utilities/privilege.js:129:34)
    at utilities.privilege.getPrivilegesFromRoles.then.privileges (/home/devop/loan-origination-system/node_modules/periodicjs.ext.user_access_control/controllers/uac.js:19:49)
    at processTicksAndRejections (internal/process/task_queues.js:86:5) 
{ err: {},
  ipinfo:
   { date: 2019-08-27T09:52:26.983Z,
     'x-forwarded-for': undefined,
     remoteAddress: '::ffff:83.45.92.211',
     originalUrl: '/load/configurations?refresh=true',
     headerHost: 'xxx.xxx.com:8788',
     userAgent:
      'Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0',
     referer: 'https://xxx.xxx.com:8788/auth/create-account',
     user:
      { email: 'xxx@xxx.com',
        username: undefined,
        firstname: undefined,
        lastname: undefined },
     osHostname: 'digifi-1' } }
```

Any suggestions on what may be causing this issues?

**Comment by hmercade** [comment]
This was indeed the problem. I had redis misconfigured in the database. 

Thank you very much!
