### ISSUE TITLE
Local installation

### ISSUE THREAD

**Issue by mikkushukla** [digifi-io/loan-origination-system#86]
I am using centOS 16.0
standalone mongo and redis running.
After executing 
`npm i && npm i periodicjs.ext.passport --save && npm i periodicjs.ext.oauth2server@10.5.21 --save`
Getting this error
```
(node:5866) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:5866) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
Mongoose: extensions.ensureIndex({ name: 1 }, { unique: true, background: true })
Mongoose: changesets.ensureIndex({ createdat: 1 }, { background: true })
(node:5866) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
Mongoose: configurations.findOne({ filepath: 'content/config/process/runtime.json' }, { sort: { filepath: -1, createdat: -1 }, projection: {} })
Mongoose: changesets.ensureIndex({ 'parent_document.id': 1 }, { background: true })
Mongoose: changesets.ensureIndex({ 'parent_document.document_type': 1 }, { background: true })
Could not initialize Periodic
Error: A valid runtime environment is required
    at /home/insit01/loan-origination-system/node_modules/periodicjs/lib/init/runtime.js:96:19
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```
Installation manual  is not compete. 
What would be the content of file `content/config/process/runtime.json`   ?

**Comment by tundraerp** [comment]
I've got it running on Ubuntu 18.04.
```
npm i
npm i periodicjs.ext.passport --save
npm i periodicjs.ext.oauth2server@10.5.21 --save
npm start development
```
Also make sure you have Node 11 installed and the correct React version. Also the configuration.json needs to be spot on. At least with the required elements like Mongo / Redis / S3.

If running locally you need to make sure Mongo is running as a replicaset and not standalone.

**Comment by mikkushukla** [comment]
I have local redis, mongo stand alone. Where I configure mongo host port.
Do I have create collections or they wll get created automatically

**Comment by tundraerp** [comment]
You need to upload the json manually. Here's my configurations json:

[configurations.zip](https://github.com/digifi-io/loan-origination-system/files/4160082/configurations.zip)

**Comment by codhah92** [comment]
@tundraerp Thanks for the input. Hey @mikkushukla , you need to set up your .env file as well as the configuration documents in your local mongo instance in order for the application to run properly. If you follow the instructions on this link (https://docs.digifi.io/docs/database-configuration), you should be able to get through the installation process.

**Comment by mikkushukla** [comment]
I am new to mongo,I am a SQL guy. How I import collections. Could please share command.

**Comment by tundraerp** [comment]
Use mongoimport:

https://docs.mongodb.com/manual/reference/program/mongoimport/#bin.mongoimport

mongoimport --host=localhost --collection=configurations --db=configuration_local --file=configurations.json --jsonArray

Also remove the *1* stuff from the filw

**Comment by mikkushukla** [comment]
What stuff you are taking about?

**Comment by tundraerp** [comment]
> What stuff you are taking about?

I removed it from the configuration file I sent you but in the docs the various document records are denoted by one two three etc... which can mess up the import.

**Comment by ashish92yadav** [comment]
Hey @mikkushukla try installing Robo 3T as mentioned here - https://docs.digifi.io/docs/database-configuration. Uploading documents to collections is easy after this. Just leave "Set Name" field blank in Connection tab. That's different from what written in the steps in the above link.

**Comment by mikkushukla** [comment]
I have tried everything as per suggestion getting below error
```
2020-02-06T15:56:25.312+0530 I NETWORK  [listener] connection accepted from 127.0.0.1:46726 #18 (7 connections now open)
2020-02-06T15:56:25.314+0530 I NETWORK  [conn18] received client metadata from 127.0.0.1:46726 conn18: { driver: { name: "nodejs|Mongoose", version: "3.4.1|5.8.11" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.4.0-104-generic" }, platform: "Node.js v12.15.0, LE" }
Mongoose: extensions.ensureIndex({ name: 1 }, { unique: true, background: true })
Mongoose: changesets.ensureIndex({ createdat: 1 }, { background: true })
(node:28689) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
Mongoose: configurations.findOne({ filepath: 'content/config/process/runtime.json' }, { sort: { filepath: -1, createdat: -1 }, projection: {} })
2020-02-06T15:56:25.334+0530 I NETWORK  [listener] connection accepted from 127.0.0.1:46728 #19 (8 connections now open)
2020-02-06T15:56:25.335+0530 I NETWORK  [conn19] received client metadata from 127.0.0.1:46728 conn19: { driver: { name: "nodejs|Mongoose", version: "3.4.1|5.8.11" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.4.0-104-generic" }, platform: "Node.js v12.15.0, LE" }
Mongoose: changesets.ensureIndex({ 'parent_document.id': 1 }, { background: true })
Could not initialize Periodic
Error: A valid runtime environment is required
    at /home/insit01/loan-origination-system/node_modules/periodicjs/lib/init/runtime.js:96:19
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
Mongoose: changesets.ensureIndex({ 'parent_document.document_type': 1 }, { background: true })
2020-02-06T15:56:35.322+0530 I NETWORK  [listener] connection accepted from 127.0.0.1:60610 #14 (3 connections now open)
2020-02-06T15:56:35.322+0530 I NETWORK  [conn14] received client metadata from 127.0.0.1:60610 conn14: { driver: { name: "nodejs|Mongoose", version: "3.4.1|5.8.11" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.4.0-104-generic" }, platform: "Node.js v12.15.0, LE" }

```

**Comment by narviii** [comment]
I'm getting 'npm ERR! Cannot read property 'match' of undefined' error when i'm running npm i periodicjs.ext.passport --save

What can be wrong?

**Comment by ganeshswinjit** [comment]
Is there any support available from Digifi to address these issues?

**Comment by Vasimk07** [comment]
![digifi-err](https://user-images.githubusercontent.com/62983015/80378912-fbeb0700-88ba-11ea-8e47-86f50d6032cf.png)

After running npm start development
It's stuck in this continuous loop of execution.
