### ISSUE TITLE
MongooseError: Could not initialize Periodic

### ISSUE THREAD

**Issue by rdurgarao** [digifi-io/loan-origination-system#94]
I setup account in mongodb.com and valid credentials, defined all credentials are correct. Its working from connect through the robomongo, on ```npm start development```. I am getting this error.

```
Mongoose: configurations.findOne({ filepath: 'content/config/process/runtime.json' }, { sort: { filepath: -1, createdat: -1 }, projection: {} })
Mongoose: changesets.ensureIndex({ 'parent_document.id': 1 }, { background: true })
Could not initialize Periodic
MongoError: cannot do raw queries on admin in atlas
    at Connection.<anonymous> (/home/ubuntu/loan-origination-system/node_modules/mongodb/lib/core/connection/pool.js:450:61)
    at Connection.emit (events.js:311:20)
    at Connection.EventEmitter.emit (domain.js:482:12)
    at processMessage (/home/ubuntu/loan-origination-system/node_modules/mongodb/lib/core/connection/connection.js:384:10)
    at TLSSocket.<anonymous> (/home/ubuntu/loan-origination-system/node_modules/mongodb/lib/core/connection/connection.js:553:15)
    at TLSSocket.emit (events.js:311:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at TLSSocket.Readable.push (_stream_readable.js:209:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23) {
  ok: 0,
  errmsg: 'cannot do raw queries on admin in atlas',
  code: 8000,
  codeName: 'AtlasError',
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: {}
}
Mongoose: changesets.ensureIndex({ 'parent_document.document_type': 1 }, { background: true })
```

**Comment by rdurgarao** [comment]
I got the solution for this problem, using older syntax of mongodb url string, works!!

Node 2.x later syntax in mongodb atlas account is working.
