### ISSUE TITLE
 The specified bucket does not exist NoSuchBucket

### ISSUE THREAD

**Issue by derbsruns** [digifi-io/loan-origination-system#96]
We finally have everything up and running however, when we try the sample machine learning process with the example data, when we get to the Choose File and continue, the process fails. We have the S3 Access Keys setup. 

Question 1: I don't see where we specifically specify an S3 bucket name?
Question 2: In order to run this test do we need to setup AWS ML and Sagemaker?

The error:

`2020-04-10T20:11:40.062Z - error: The specified bucket does not exist NoSuchBucket: The specified bucket does not exist
    at Request.extractError (/home/ubuntu/digifi/loan-origination-system/node_modules/aws-sdk/lib/services/s3.js:835:35)
    at Request.callListeners (/home/ubuntu/digifi/loan-origination-system/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/ubuntu/digifi/loan-origination-system/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/ubuntu/digifi/loan-origination-system/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/ubuntu/digifi/loan-origination-system/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ubuntu/digifi/loan-origination-system/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ubuntu/digifi/loan-origination-system/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ubuntu/digifi/loan-origination-system/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ubuntu/digifi/loan-origination-system/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/ubuntu/digifi/loan-origination-system/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/home/ubuntu/digifi/loan-origination-system/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/ubuntu/digifi/loan-origination-system/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/ubuntu/digifi/loan-origination-system/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ubuntu/digifi/loan-origination-system/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ubuntu/digifi/loan-origination-system/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ubuntu/digifi/loan-origination-system/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ubuntu/digifi/loan-origination-system/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/ubuntu/digifi/loan-origination-system/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at callNextListener (/home/ubuntu/digifi/loan-origination-system/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at IncomingMessage.onEnd (/home/ubuntu/digifi/loan-origination-system/node_modules/aws-sdk/lib/event_listeners.js:307:13)
    at IncomingMessage.emit (events.js:198:15)
    at IncomingMessage.EventEmitter.emit (domain.js:481:20)
    at endReadableNT (_stream_readable.js:1139:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
{ err:
   { message: 'The specified bucket does not exist',
     code: 'NoSuchBucket',
     region: null,
     time: 2020-04-10T20:11:40.059Z,
     requestId: '9F1CD9602AE27452',
     extendedRequestId:
      '4iBPTZIIFY6XQVnZ5QvIrM2bml1TWvcpJ8y/yCxxx83tddmapA2qqRmo3O0QiGMuld+nIwCC/CY=',
     cfId: undefined,
     statusCode: 404,
     retryable: false,
     retryDelay: 96.04089943912469 },
  ipinfo:
   { date: 2020-04-10T20:11:40.062Z,
     'x-forwarded-for': undefined,
     remoteAddress: '::ffff:xx.205.125.109',
     originalUrl:
      '/ml/api/models/5e90d2ef2f3138630f7909f8/data_source?upload=true',
     headerHost: 'xxx.xxx.com:8788',
     userAgent:
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36',
     referer:
      'https://xxx.xxx.com:8788/ml/models/5e90d2ef2f3138630f7909f8/training/historical_data_binary',
     user:
      { email: 'x@x.com',
        username: undefined,
        firstname: undefined,
        lastname: undefined },
     osHostname: 'ip-x-x-x-x' } }
`

**Comment by derbsruns** [comment]
@tundraerp I see that you were able to get this fully configured and running. Do you know the answer to this or perhaps know the proper format for the S3 bucket settings?

**Comment by Vasimk07** [comment]
Hey did u the solve the issue , what was the solution ?

**Comment by chetanbothra** [comment]
Hi Team,

Please let us know how do we define our own custom bucket name. 
We are having a similar issue. 

Thanks in Advance !
