### ISSUE TITLE
Cannot find module 'periodicjs.ext.dblogger

### ISSUE THREAD

**Issue by Ankireddybitcot** [digifi-io/loan-origination-system#99]
## Doing this setup on server,we are getting module not found
when run ```npm start development```
 * we are getting folllowing errors about periodicjs
```
{
  message: "Cannot find module 'periodicjs.ext.dblogger/resources/async_routers/index'\n" +
    'Require stack:\n' +
    '- /home/ubuntu/loan-origination-system/node_modules/periodicjs/lib/init/config.js\n' +
    '- /home/ubuntu/loan-origination-system/node_modules/periodicjs/lib/init/index.js\n' +
    '- /home/ubuntu/loan-origination-system/node_modules/periodicjs/lib/periodicClass.js\n' +
    '- /home/ubuntu/loan-origination-system/node_modules/periodicjs/lib/periodic.js\n' +
    '- /home/ubuntu/loan-origination-system/node_modules/periodicjs/index.js\n' +
    '- /home/ubuntu/loan-origination-system/index.js',
  stack: "Error: Cannot find module 'periodicjs.ext.dblogger/resources/async_routers/index'\n" +
    'Require stack:\n' +
    '- /home/ubuntu/loan-origination-system/node_modules/periodicjs/lib/init/config.js\n' +
    '- /home/ubuntu/loan-origination-system/node_modules/periodicjs/lib/init/index.js\n' +
    '- /home/ubuntu/loan-origination-system/node_modules/periodicjs/lib/periodicClass.js\n' +
    '- /home/ubuntu/loan-origination-system/node_modules/periodicjs/lib/periodic.js\n' +
    '- /home/ubuntu/loan-origination-system/node_modules/periodicjs/index.js\n' +
    '- /home/ubuntu/loan-origination-system/index.js\n' +
    '    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)\n' +
    '    at Function.Module._load (internal/modules/cjs/loader.js:840:27)\n' +
    '    at Module.require (internal/modules/cjs/loader.js:1019:19)\n' +
    '    at require (internal/modules/cjs/helpers.js:77:18)\n' +
    '    at EventEmitter.<anonymous> (/home/ubuntu/loan-origination-system/node_modules/periodicjs/lib/init/config.js:783:15)\n' +
    '    at EventEmitter.emit (events.js:322:22)\n' +
    '    at EventEmitter.emit (domain.js:482:12)\n' +
    '    at /home/ubuntu/loan-origination-system/node_modules/periodicjs/lib/init/server.js:173:19\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at Proxy.emitConfigurationComplete (/home/ubuntu/loan-origination-system/node_modules/periodicjs/lib/init/server.js:171:10)\n' +
    '    at Proxy.initializeServers (/home/ubuntu/loan-origination-system/node_modules/periodicjs/lib/init/server.js:189:33)\n' +
    '    at /home/ubuntu/loan-origination-system/node_modules/periodicjs/node_modules/promisie/index.js:79:18\n' +
    '    at series (/home/ubuntu/loan-origination-system/node_modules/periodicjs/node_modules/promisie/utility/series_generator.js:22:24)\n' +
    '    at series.next (<anonymous>)\n' +
    '    at iterate (/home/ubuntu/loan-origination-system/node_modules/periodicjs/node_modules/promisie/utility/iterator.js:8:27)',
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/ubuntu/loan-origination-system/node_modules/periodicjs/lib/init/config.js',
    '/home/ubuntu/loan-origination-system/node_modules/periodicjs/lib/init/index.js',
    '/home/ubuntu/loan-origination-system/node_modules/periodicjs/lib/periodicClass.js',
    '/home/ubuntu/loan-origination-system/node_modules/periodicjs/lib/periodic.js',
    '/home/ubuntu/loan-origination-system/node_modules/periodicjs/index.js',
    '/home/ubuntu/loan-origination-system/index.js'
  ]
}
```

**Comment by tsx-barrytallis** [comment]
@Ankireddybitcot any resolution on this?  Getting the same issue

**Comment by saisk73** [comment]
> @Ankireddybitcot any resolution on this? Getting the same issue

Delete node_modules install node_modules again with same versions in the documentation.
